name: FeatureBranch Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      # Cache Gradle dependencies (including wrapper) and build outputs
      - name: Cache Gradle caches
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: build
        run: ./gradlew build -x test -PnexusSnapshotUrl=${{ secrets.NEXUS_SNAPSHOT_URL }} -PnexusUrl=${{ secrets.NEXUS_URL }} -PnexusUser=${{ secrets.NEXUS_USER }} -PnexusPassword=${{ secrets.NEXUS_PASSWORD }}

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore cached build files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: run tests
        run: ./gradlew test -PnexusSnapshotUrl=${{ secrets.NEXUS_SNAPSHOT_URL }} -PnexusUrl=${{ secrets.NEXUS_URL }} -PnexusUser=${{ secrets.NEXUS_USER }} -PnexusPassword=${{ secrets.NEXUS_PASSWORD }}

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Restore cached build files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: publish repo
        run: ./gradlew publish -PnexusSnapshotUrl=${{ secrets.NEXUS_SNAPSHOT_URL }} -PnexusUrl=${{ secrets.NEXUS_URL }} -PnexusUser=${{ secrets.NEXUS_USER }} -PnexusPassword=${{ secrets.NEXUS_PASSWORD }}